// POST test to add car
// POST http://localhost:5000/cars/{"type":"compact","make":"Fiat 500","model":2022,"registration":"YY72FUN"}
POST http://localhost:5000/cars/{"make":"Mazda MX-3","model":"2017","registration":"MX17MZD","type":"compact"}


// url format for query make.
//GET http://localhost:5000/cars/?"Land Rover"


// url query for any key ?key=value
// GET http://localhost:5000/cars/find/?type=4x4&&
// url must be string without special chars (no "" no spaces etc.

// DELETE test - do via id of car as saved in DB - call verifies car exists before delete
// DELETE http://localhost:5000/cars/63fd052d2704c13c2c58cfbc