// POST test to add car
// POST http://localhost:5000/cars{"type":"saloon","make":"Ford Focus","model":2019,"registration":"YY69WWW"}


// url format for query make.
//GET http://localhost:5000/cars/?"Land Rover"


// url query for any key ?key=value
// GET http://localhost:5000/cars/find/?make=Land%20Rover&model=2011
// url must be string without special chars (no "" no spaces etc.

// DELETE test - do via id of car as saved in DB - call verifies car exists before delete
//DELETE http://localhost:5000/cars/63f63481191e20c21a98636b